version: '3'
services:
  db:
    image: mysql
    restart: unless-stopped
    environment: 
      - MYSQL_DATABASE=dejavu
      - MYSQL_ROOT_PASSWORD=PnKKvj21RziO2OKf
    volumes:
      - mysql_db_volume2:/var/lib/mysql
  python:
    build:
      dockerfile: python.Dockerfile
    environment: 
      - MYSQL_DB_CONFIG_PATH=dejavu.cnf.dev.SAMPLE
    ports:
      - "0.0.0.0:5678:5678"
    depends_on:
      - db
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=PnKKvj21RziO2OKf
    ports:
      - "0.0.0.0:8092:80"

volumes:
  mysql_db_volume2: