version: '3'
services:
  db:
    image: mysql
    restart: unless-stopped
    env_file:
      - development.env
    volumes:
      - mysql_db_volume:/var/lib/mysql
  python:
    env_file:
      - development.env
    build:
      dockerfile: python.Dockerfile
    ports:
      - "0.0.0.0:5678:5678"
    depends_on:
      - db
  phpmyadmin:
    env_file:
      - development.env
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "0.0.0.0:8092:80"

volumes:
  mysql_db_volume: